# Generated by Django 3.0.6 on 2020-05-25 04:12

from django.db import migrations, models
import django.utils.timezone
import service_user.models.login_module
import utils.hash
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidUserNameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='사용자 이름')),
                ('avail', models.BooleanField(default=True, verbose_name='설정하기')),
            ],
            options={
                'verbose_name': '불가한 사용자 이름',
                'verbose_name_plural': '불가한 사용자 이름들',
                'db_table': 'invalid_username',
            },
        ),
        migrations.CreateModel(
            name='LoginModuleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('description', models.TextField(verbose_name='설명')),
                ('image', models.ImageField(upload_to=service_user.models.login_module.upload_to, verbose_name='이미지')),
                ('public_option', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('order', models.IntegerField(default=1, verbose_name='순서')),
            ],
            options={
                'verbose_name': '로그인 모듈',
                'verbose_name_plural': '로그인 모듈들',
                'db_table': 'login_module',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='사용자 이름')),
                ('password', models.CharField(max_length=254, verbose_name='사용자 암호')),
                ('email', models.EmailField(default=None, max_length=254, null=True, verbose_name='이메일')),
                ('status', models.CharField(choices=[('NORMAL', '일반'), ('HOLIDAY', '휴면'), ('EXIT', '탈퇴')], default='NORMAL', max_length=20, verbose_name='상태')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='번호')),
                ('session_id', models.CharField(default=utils.hash.HashUtil.get_session_id, editable=False, max_length=254, unique=True, verbose_name='세션')),
                ('token_id', models.CharField(default=utils.hash.HashUtil.get_token_id, editable=False, max_length=254, unique=True, verbose_name='토큰')),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='가입 날짜')),
                ('login_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='접속 날짜')),
                ('exit_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='탈퇴 날짜')),
            ],
            options={
                'verbose_name': '이용자',
                'verbose_name_plural': '이용자들',
                'db_table': 'user',
            },
        ),
        migrations.AddIndex(
            model_name='usermodel',
            index=models.Index(fields=['user_id'], name='user_user_id_31c9cf_idx'),
        ),
        migrations.AddIndex(
            model_name='usermodel',
            index=models.Index(fields=['user_id', 'session_id'], name='user_user_id_afbd77_idx'),
        ),
        migrations.AddIndex(
            model_name='usermodel',
            index=models.Index(fields=['username'], name='user_usernam_b79065_idx'),
        ),
        migrations.AddIndex(
            model_name='invalidusernamemodel',
            index=models.Index(fields=['username'], name='invalid_use_usernam_2ca477_idx'),
        ),
    ]
