# Generated by Django 3.0.6 on 2020-05-25 04:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import service_application.models.application
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True, verbose_name='앱 번호')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='이름')),
                ('description', models.TextField(verbose_name='설명')),
                ('url', models.CharField(max_length=200, unique=True, verbose_name='앱 주소')),
                ('icon', models.ImageField(default=None, null=True, upload_to=service_application.models.application.ApplicationModelSetup.icon_path, validators=[service_application.models.application.ApplicationModelSetup.icon_dimension_validator], verbose_name='아이콘 경로')),
                ('preview_image', models.ImageField(blank=True, default=None, null=True, upload_to=service_application.models.application.ApplicationModelSetup.preview_image_path, validators=[service_application.models.application.ApplicationModelSetup.preview_image_size_validator], verbose_name='미리보기 경로')),
                ('public_option', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='배포 날짜')),
            ],
            options={
                'verbose_name': '어플리케이션',
                'verbose_name_plural': '어플리케이션들',
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='UsingApplicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='순서')),
                ('installed_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='설치 날짜')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_application.ApplicationModel', verbose_name='어플리케이션')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_user.UserModel', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용중인 어플리케이션',
                'verbose_name_plural': '사용중인 어플리케이션들',
                'db_table': 'using_application',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='applicationmodel',
            index=models.Index(fields=['app_id'], name='application_app_id_a62bea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usingapplicationmodel',
            unique_together={('application', 'user')},
        ),
    ]
