export const INIT = "INIT";
export const STATUS_INIT = "STATUS_INIT";

// Login page
export const LOGIN_PAGE__LOADING = "LOGIN_PAGE__LOADING";

export const LOGIN_PAGE__INIT = "LOGIN_PAGE__INIT";
export const LOGIN_PAGE__CHANGING_USERNAME = "LOGIN_PAGE__CHANGING_USERNAME";
export const LOGIN_PAGE__CHANGING_PASSWORD = "LOGIN_PAGE__CHANGING_PASSWORD";
export const LOGIN_PAGE__VALIDATING__FORM_BLANK = "LOGIN_PAGE__VALIDATING__FORM_BLANK";

export const LOGIN_PAGE__LOGIN = "LOGIN_PAGE__LOGIN";
export const LOGIN_PAGE__LOGIN_INVALID = "LOGIN_PAGE__LOGIN_INVALID";
export const LOGIN_PAGE__LOGIN_ERROR = "LOGIN_PAGE__LOGIN_ERROR";

// Join Page
export const JOIN_PAGE__LOADING = "JOIN_PAGE__LOADING";

export const JOIN_PAGE__INIT = "JOIN_PAGE__INIT";
export const JOIN_PAGE__CHANGING_USERNAME = "JOIN_PAGE__CHANGING_USERNAME";
export const JOIN_PAGE__CHANGING_PASSWORD = "JOIN_PAGE__CHANGING_PASSWORD";
export const JOIN_PAGE__CHANGING_PASSWORD_CHECK = "JOIN_PAGE__CHANGING_PASSWORD_CHECK";
export const JOIN_PAGE__CHANGING_EMAIL = "JOIN_PAGE__CHANGING_EMAIL";
export const JOIN_PAGE__VALIDATING__FORM_BLANK = "JOIN_PAGE__VALIDATING__FORM_BLANK";
export const JOIN_PAGE__VALIDATING__USERNAME_IS_NOT_VERIFIED = "JOIN_PAGE__VALIDATING__USERNAME_IS_NOT_VERIFIED";
export const JOIN_PAGE__VALIDATING__USERNAME_IS_BLANK = "JOIN_PAGE__VALIDATING__USERNAME_IS_BLANK";

export const JOIN_PAGE__VERIFYING_USERNAME = "JOIN_PAGE__VERIFYING_USERNAME";
export const JOIN_PAGE__VERIFYING_USERNAME_INVALID = "JOIN_PAGE__VERIFYING_USERNAME_INVALID";
export const JOIN_PAGE__VERIFYING_USERNAME_ERROR = "JOIN_PAGE__VERIFYING_USERNAME_ERROR";

export const JOIN_PAGE__JOIN = "JOIN_PAGE__JOIN";
export const JOIN_PAGE__JOIN_INVALID = "JOIN_PAGE__JOIN_INVALID";
export const JOIN_PAGE__JOIN_ERROR = "JOIN_PAGE__JOIN_ERROR";

// Main Page
export const MAIN_PAGE__LOADING = "MAIN_PAGE__LOADING";
export const MAIN_PAGE__LOADING_INVALID = "MAIN_PAGE__LOADING_INVALID";
export const MAIN_PAGE__LOADING_ERROR = "MAIN_PAGE__LOADING_ERROR";

export const MAIN_PAGE__INIT = "MAIN_PAGE__INIT";

export const MAIN_PAGE__RUN = "MAIN_PAGE__RUN";

export const MAIN_PAGE__UNINSTALL = "MAIN_PAGE__UNINSTALL";
export const MAIN_PAGE__UNINSTALL_INVALID = "MAIN_PAGE__UNINSTALL_INVALID";
export const MAIN_PAGE__UNINSTALL_ERROR = "MAIN_PAGE__UNINSTALL_ERROR";

// Profile Page
export const PROFILE_PAGE__LOADING = "PROFILE_PAGE__LOADED";
export const PROFILE_PAGE__LOADING_INVALID = "PROFILE_PAGE__LOADING_INVALID";
export const PROFILE_PAGE__LOADING_ERROR = "PROFILE_PAGE__LOADING_ERROR";
export const PROFILE_PAGE__LOADING_USING_APPLICATIONS = "PROFILE_PAGE__LOADING_USING_APPLICATIONS";
export const PROFILE_PAGE__LOADING_USING_APPLICATIONS_INVALID = "PROFILE_PAGE__LOADING_USING_APPLICATIONS_INVALID";
export const PROFILE_PAGE__LOADING_USING_APPLICATIONS_ERROR = "PROFILE_PAGE__LOADING_USING_APPLICATIONS_ERROR";

export const PROFILE_PAGE__INIT = "PROFILE_PAGE__INIT";
export const PROFILE_PAGE__CHANGING_USERNAME = "PROFILE_PAGE__CHANGING_USERNAME";
export const PROFILE_PAGE__CHANGING_EMAIL = "PROFILE_PAGE__CHANGING_EMAIL";
export const PROFILE_PAGE__CHANGING_EXIT_APPROVAL = "PROFILE_PAGE__CHANGING_EXIT_APPROVAL";
export const PROFILE_PAGE__VALIDATING__USERNAME_IS_NOT_VERIFIED = "PROFILE_PAGE__VALIDATING__USERNAME_IS_NOT_VERIFIED";
export const PROFILE_PAGE__VALIDATING__USERNAME_IS_BLANK = "PROFILE_PAGE__VALIDATING__USERNAME_IS_BLANK";
export const PROFILE_PAGE__VALIDATING__USERNAME_IS_NOT_CHANGED = "PROFILE_PAGE__VALIDATING__USERNAME_IS_NOT_CHANGED"
export const PROFILE_PAGE__VALIDATING__FORM_BLANK = "PROFILE_PAGE__VALIDATING__FORM_BLANK";
export const PROFILE_PAGE__VALIDATING__EXIT_APPROVAL_IS_NOT_CHECKED = "PROFILE_PAGE__VALIDATING__EXIT_APPROVAL_IS_NOT_CHECKED";
export const PROFILE_PAGE__VALIDATING__NOTHING_CHANGED = "PROFILE_PAGE__VALIDATING__NOTHING_CHANGED";
export const PROFILE_PAGE__RESET = "PROFILE_PAGE__RESET"

export const PROFILE_PAGE__VERIFYING_USERNAME = "PROFILE_PAGE__VERIFYING_USERNAME";
export const PROFILE_PAGE__VERIFYING_USERNAME_INVALID = "PROFILE_PAGE__VERIFYING_USERNAME_INVALID";
export const PROFILE_PAGE__VERIFYING_USERNAME_ERROR = "PROFILE_PAGE__VERIFYING_USERNAME_ERROR";

export const PROFILE_PAGE__UPDATE = "PROFILE_PAGE__UPDATE";
export const PROFILE_PAGE__UPDATE_INVALID = "PROFILE_PAGE__UPDATE_INVALID";
export const PROFILE_PAGE__UPDATE_ERROR = "PROFILE_PAGE__UPDATE_ERROR";

export const PROFILE_PAGE__EXIT = "PROFILE_PAGE__EXIT";
export const PROFILE_PAGE__EXIT_INVALID = "PROFILE_PAGE__EXIT_INVALID";
export const PROFILE_PAGE__EXIT_ERROR = "PROFILE_PAGE__EXIT_ERROR";

// Password Page
export const PASSWORD_PAGE__LOADING = "PASSWORD_PAGE__LOADING";
export const PASSWORD_PAGE__LOADING_INVALID = "PASSWORD_PAGE__LOADING_INVALID";
export const PASSWORD_PAGE__LOADING_ERROR = "PASSWORD_PAGE__LOADING_ERROR";

export const PASSWORD_PAGE__INIT = "PASSWORD_PAGE__INIT";
export const PASSWORD_PAGE__CHANGING_PASSWORD = "PASSWORD_PAGE__CHANGING_PASSWORD";
export const PASSWORD_PAGE__CHANGING_NEW_PASSWORD = "PASSWORD_PAGE__CHANGING_NEW_PASSWORD";
export const PASSWORD_PAGE__CHANGING_NEW_PASSWORD_CHECK = "PASSWORD_PAGE__CHANGING_NEW_PASSWORD_CHECK";
export const PASSWORD_PAGE__VALIDATING__FORM_BLANK = "PASSWORD_PAGE__VALIDATING__FORM_BLANK";

export const PASSWORD_PAGE__UPDATE = "PASSWORD_PAGE__UPDATE";
export const PASSWORD_PAGE__UPDATE_INVALID = "PASSWORD_PAGE__UPDATE_INVALID";
export const PASSWORD_PAGE__UPDATE_ERROR = "PASSWORD_PAGE__UPDATE_ERROR";

// Application Page
export const APPLICATION_PAGE__LOADING = "APPLICATION_PAGE__LOADING";
export const APPLICATION_PAGE__LOADING_MORE = "APPLICATION_PAGE__LOADING_MORE";
export const APPLICATION_PAGE__LOADING_INVALID = "APPLICATION_PAGE__LOADING_INVALID";
export const APPLICATION_PAGE__LOADING_ERROR = "APPLICATION_PAGE__LOADING_ERROR";

export const APPLICATION_PAGE__INIT = "APPLICATION_PAGE__INIT";
export const APPLICATION_PAGE__CHANGING_QUERY = "APPLICATION_PAGE__CHANGING_QUERY";

export const APPLICATION_PAGE__INSTALL = "APPLICATION_PAGE__INSTALL";
export const APPLICATION_PAGE__INSTALL_INVALID = "APPLICATION_PAGE__INSTALL_INVALID";
export const APPLICATION_PAGE__INSTALL_ERROR = "APPLICATION_PAGE__INSTALL_ERROR";

export const APPLICATION_PAGE__UNINSTALL = "APPLICATION_PAGE__UNINSTALL";
export const APPLICATION_PAGE__UNINSTALL_INVALID = "APPLICATION_PAGE__UNINSTALL_INVALID";
export const APPLICATION_PAGE__UNINSTALL_ERROR = "APPLICATION_PAGE__UNINSTALL_ERROR";

// Application Detail Page
export const APPLICATION_DETAIL_PAGE__LOADING = "APPLICATION_DETAIL_PAGE__LOADING";
export const APPLICATION_DETAIL_PAGE__LOADING_INVALID = "APPLICATION_DETAIL_PAGE__LOADING_INVALID";
export const APPLICATION_DETAIL_PAGE__LOADING_ERROR = "APPLICATION_DETAIL_PAGE__LOADING_ERROR";

export const APPLICATION_DETAIL_PAGE__INIT = "APPLICATION_DETAIL_PAGE__INIT"

export const APPLICATION_DETAIL_PAGE__RUN = "APPLICATION_DETAIL_PAGE__RUN";

export const APPLICATION_DETAIL_PAGE__INSTALL = "APPLICATION_DETAIL_PAGE__INSTALL";
export const APPLICATION_DETAIL_PAGE__INSTALL_INVALID = "APPLICATION_DETAIL_PAGE__INSTALL_INVALID";
export const APPLICATION_DETAIL_PAGE__INSTALL_ERROR = "APPLICATION_DETAIL_PAGE__INSTALL_ERROR";

export const APPLICATION_DETAIL_PAGE__UNINSTALL = "APPLICATION_DETAIL_PAGE__UNINSTALL";
export const APPLICATION_DETAIL_PAGE__UNINSTALL_INVALID = "APPLICATION_DETAIL_PAGE__UNINSTALL_INVALID";
export const APPLICATION_DETAIL_PAGE__UNINSTALL_ERROR = "APPLICATION_DETAIL_PAGE__UNINSTALL_ERROR";
